enum TileType
{
	LEFT_TILE = 0,
	UP_TILE = 1,
	RIGHT_TILE = 2,
	DOWN_TILE = 3,
	VERTICAL_PIPE_TILE = 4,
	HORIZONTAL_PIPE_TILE = 5,
	TOP_TILE = 6,
	BOT_TILE = 7,
	TOP_LEFT_TILE = 8,
	TOP_RIGHT_TILE = 9,
	BOT_LEFT_TILE = 10,
	BOT_RIGHT_TILE = 11,
	RIGHT_BORDER_TILE = 12,
	LEFT_BORDER_TILE = 13,
	FOOD = 14
};